# fly.toml app configuration file generated for redgombo on 2023-05-18T02:39:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redgombo"
primary_region = "nrt"
[build]
  image = "jc3wrld999/redgombo:1.0"
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
